CREATE TRIGGER SetCodeI18N
    ON Menus AFTER INSERT
    AS
BEGIN
UPDATE Menus
SET CodeI18N = CONCAT('I18N_', UPPER(REPLACE(INSERTED.Name, ' ', ''))) FROM INSERTED
WHERE Menus.Id = INSERTED.Id;
END;

ALTER TABLE Menus
    ADD CONSTRAINT DF_Menus_UpdatedAt DEFAULT (GETDATE()) FOR UpdatedAt;

ALTER TABLE Menus
    ADD CONSTRAINT DF_Menus_CreatedAt DEFAULT (GETDATE()) FOR CreatedAt;
